#!/usr/bin/bash

echo "start purge"

for arg in "$@"; do
  echo "purge $arg"
  python3 purge.py "$arg"

  ret=$?

  if [ $ret -eq 2 ]; then
    echo "empty folder"
  elif [ $ret -ne 0 ]; then
    echo "ERROR"
    exit $ret
  fi
done

echo "done purge"
